server:
  port: ${SERVER_PORT:8082}
spring:
  rabbitmq:
    addresses: 47.115.115.138:5672
    username: admin
    password: 111111
    connection-timeout: 15000
    virtual-host: /
    #消息发送到交换机确认机制，是否确认回调
    publisher-confirm: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小消费者数量
        max-concurrency: 1 #指定最大消费者数量
        retry:
          enabled: true #是否支持重试

